backend:
  name: github
  repo: Chrysostomos00/CCP
  branch: master
  base_url: https://ccp-five-chi.vercel.app
  auth_endpoint: api/auth

media_folder: "public/uploads"
public_folder: "/uploads"

collections:
  - name: "news"
    label: "News & Events"
    folder: "src/content/news"
    create: true
    extension: "json"
    format: "json"
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Category", name: "category", widget: "select", options: ["News", "Event", "Press Release", "Announcement"]}
      - {label: "Featured Image", name: "thumbnail", widget: "image", required: false}
      - {label: "Body", name: "body", widget: "markdown"}
